@ref ./api.login.http

{{
  const fs = require('fs');
  $global.LoginToken = fs.readFileSync('./token.txt', 'utf8'); // ✅ Read token back
}}

### @name Request to call token 

// write your request here
GET {{baseURL}}/users?page=2
Authorization: Bearer {{$global.LoginToken}}

{{
  const assert = require('assert');
  const jsonData = response.parsedBody;
  test("Status code is 200", () => {
    assert.equal(response.statusCode, 200);
  });
}}
